@FinanceTracker_API_HostAddress = http://localhost:5270

# Health Check Endpoint
GET {{FinanceTracker_API_HostAddress}}/api/health
Accept: application/json

###
# Get All Categories Endpoint
GET {{FinanceTracker_API_HostAddress}}/api/categories
Accept: application/json

###
# Create Category Endpoint
POST {{FinanceTracker_API_HostAddress}}/api/categories
Content-Type: application/json
Accept: application/json

{
  "name": "test"
}

###
# Update Category Endpoint
PUT {{FinanceTracker_API_HostAddress}}/api/categories
Content-Type: application/json
Accept: application/json

{
  "id": "00000000-0000-0000-0000-000000000000",
  "name": "updated test"
}

###
# Delete Category Endpoint
DELETE {{FinanceTracker_API_HostAddress}}/api/categories/00000000-0000-0000-0000-000000000000
Accept: application/json

###